/* eslint-disable prettier/prettier */
export const conditionImages = {
  'Sunny': require('../assets/weatherconditionimgs/sunny-day.jpg'),
  'Clear ': require('../assets/weatherconditionimgs/sunny-day.jpg'),
  'Partly cloudy': require('../assets/weatherconditionimgs/partly-cloudy.png'),
  'Cloudy': require('../assets/weatherconditionimgs/cloudy-day.jpg'),
  'Overcast': require('../assets/weatherconditionimgs/overcast-day.jpg'),
  'Mist': require('../assets/weatherconditionimgs/mist-day.jpg'),
  'Patchy rain possible': require('../assets/weatherconditionimgs/patchy-rain-day.jpg'),
  'Patchy snow possible': require('../assets/weatherconditionimgs/patchy-snow-day.jpg'),
  'Patchy sleet possible': require('../assets/weatherconditionimgs/patchy-snow-day.jpg'),
  'Thundery outbreaks possible': require('../assets/weatherconditionimgs/thundery-outbreaks-possible.jpg'),
  'Blowing snow': require('../assets/weatherconditionimgs/blowing-snow.jpg'),
  'Blizzard': require('../assets/weatherconditionimgs/blizzard.jpg'),
  'Fog': require('../assets/weatherconditionimgs/mist-day.jpg'),
  'Freezing fog': require('../assets/weatherconditionimgs/freezing-fog.jpg'),
  'Patchy light drizzle': require('../assets/weatherconditionimgs/patchy-light-drizzle.jpg'),
  'Light drizzle': require('../assets/weatherconditionimgs/patchy-light-drizzle.jpg'),
  'Freezing drizzle': require('../assets/weatherconditionimgs/patchy-freezing-drizzle-possible.jpg'),
  'Heavy freezing drizzle': require('../assets/weatherconditionimgs/patchy-freezing-drizzle-possible.jpg'),
  'Patchy light rain': require('../assets/weatherconditionimgs/patchy-rain-day.jpg'),
  'Light rain': require('../assets/weatherconditionimgs/patchy-rain-day.jpg'),
  'Moderate rain at times': require('../assets/weatherconditionimgs/moderate-rain-at-times.jpg'),
  'Moderate rain': require('../assets/weatherconditionimgs/moderate-rain-at-times.jpg'),
  'Heavy rain at times': require('../assets/weatherconditionimgs/heavy-rain.jpg'),
  'Heavy rain': require('../assets/weatherconditionimgs/heavy-rain.jpg'),
  'Light freezing rain': require('../assets/weatherconditionimgs/light-freezing-rain.jpg'),
  'Moderate or heavy freezing rain': require('../assets/weatherconditionimgs/light-freezing-rain.jpg'),
};
//   {
//     code: 1204,
//     day: 'Light sleet',
//     night: 'Light sleet',
//     icon: 317,
//   },
//   {
//     code: 1207,
//     day: 'Moderate or heavy sleet',
//     night: 'Moderate or heavy sleet',
//     icon: 320,
//   },
//   {
//     code: 1210,
//     day: 'Patchy light snow',
//     night: 'Patchy light snow',
//     icon: 323,
//   },
//   {
//     code: 1213,
//     day: 'Light snow',
//     night: 'Light snow',
//     icon: 326,
//   },
//   {
//     code: 1216,
//     day: 'Patchy moderate snow',
//     night: 'Patchy moderate snow',
//     icon: 329,
//   },
//   {
//     code: 1219,
//     day: 'Moderate snow',
//     night: 'Moderate snow',
//     icon: 332,
//   },
//   {
//     code: 1222,
//     day: 'Patchy heavy snow',
//     night: 'Patchy heavy snow',
//     icon: 335,
//   },
//   {
//     code: 1225,
//     day: 'Heavy snow',
//     night: 'Heavy snow',
//     icon: 338,
//   },
//   {
//     code: 1237,
//     day: 'Ice pellets',
//     night: 'Ice pellets',
//     icon: 350,
//   },
//   {
//     code: 1240,
//     day: 'Light rain shower',
//     night: 'Light rain shower',
//     icon: 353,
//   },
//   {
//     code: 1243,
//     day: 'Moderate or heavy rain shower',
//     night: 'Moderate or heavy rain shower',
//     icon: 356,
//   },
//   {
//     code: 1246,
//     day: 'Torrential rain shower',
//     night: 'Torrential rain shower',
//     icon: 359,
//   },
//   {
//     code: 1249,
//     day: 'Light sleet showers',
//     night: 'Light sleet showers',
//     icon: 362,
//   },
//   {
//     code: 1252,
//     day: 'Moderate or heavy sleet showers',
//     night: 'Moderate or heavy sleet showers',
//     icon: 365,
//   },
//   {
//     code: 1255,
//     day: 'Light snow showers',
//     night: 'Light snow showers',
//     icon: 368,
//   },
//   {
//     code: 1258,
//     day: 'Moderate or heavy snow showers',
//     night: 'Moderate or heavy snow showers',
//     icon: 371,
//   },
//   {
//     code: 1261,
//     day: 'Light showers of ice pellets',
//     night: 'Light showers of ice pellets',
//     icon: 374,
//   },
//   {
//     code: 1264,
//     day: 'Moderate or heavy showers of ice pellets',
//     night: 'Moderate or heavy showers of ice pellets',
//     icon: 377,
//   },
//   {
//     code: 1273,
//     day: 'Patchy light rain with thunder',
//     night: 'Patchy light rain with thunder',
//     icon: 386,
//   },
//   {
//     code: 1276,
//     day: 'Moderate or heavy rain with thunder',
//     night: 'Moderate or heavy rain with thunder',
//     icon: 389,
//   },
//   {
//     code: 1279,
//     day: 'Patchy light snow with thunder',
//     night: 'Patchy light snow with thunder',
//     icon: 392,
//   },
//   {
//     code: 1282,
//     day: 'Moderate or heavy snow with thunder',
//     night: 'Moderate or heavy snow with thunder',
//     icon: 395,
//   },
