/* eslint-disable prettier/prettier */
export const weatherIcons = {
  'Sunny': require('../assets/icons/conditionIcons/113.png'),
  'Clear': require('../assets/icons/conditionIcons/116.png'),
  'Partly cloudy': require('../assets/icons/conditionIcons/119.png'),
  'Cloudy': require('../assets/icons/conditionIcons/122.png'),
  'Overcast': require('../assets/icons/conditionIcons/143.png'),
  'Mist': require('../assets/icons/conditionIcons/176.png'),
  'Patchy rain possible': require('../assets/icons/conditionIcons/179.png'),
  'Patchy rain nearby': require('../assets/icons/conditionIcons/182.png'),
  'Patchy snow possible': require('../assets/icons/conditionIcons/182.png'),
  'Patchy sleet possible': require('../assets/icons/conditionIcons/185.png'),
  'Thundery outbreaks possible': require('../assets/icons/conditionIcons/200.png'),
  'Blowing snow': require('../assets/icons/conditionIcons/227.png'),
  'Blizzard': require('../assets/icons/conditionIcons/230.png'),
  'Fog': require('../assets/icons/conditionIcons/248.png'),
  'Freezing fog': require('../assets/icons/conditionIcons/260.png'),
  'Patchy light drizzle': require('../assets/icons/conditionIcons/263.png'),
  'Light drizzle': require('../assets/icons/conditionIcons/266.png'),
  'Freezing drizzle': require('../assets/icons/conditionIcons/281.png'),
  'Heavy freezing drizzle': require('../assets/icons/conditionIcons/284.png'),
  'Patchy light rain': require('../assets/icons/conditionIcons/293.png'),
  'Light rain': require('../assets/icons/conditionIcons/296.png'),
  'Moderate rain at times': require('../assets/icons/conditionIcons/299.png'),
  'Moderate rain': require('../assets/icons/conditionIcons/302.png'),
  'Heavy rain at times': require('../assets/icons/conditionIcons/305.png'),
  'Heavy rain': require('../assets/icons/conditionIcons/308.png'),
  'Light freezing rain': require('../assets/icons/conditionIcons/311.png'),
  'Moderate or heavy freezing rain': require('../assets/icons/conditionIcons/314.png'),
  'Light sleet': require('../assets/icons/conditionIcons/317.png'),
  'Moderate or heavy sleet': require('../assets/icons/conditionIcons/320.png'),
  'Patchy light snow': require('../assets/icons/conditionIcons/323.png'),
  'Light snow': require('../assets/icons/conditionIcons/326.png'),
  'Patchy moderate snow': require('../assets/icons/conditionIcons/329.png'),
  'Moderate snow': require('../assets/icons/conditionIcons/332.png'),
  'Patchy heavy snow': require('../assets/icons/conditionIcons/335.png'),
  'Heavy snow': require('../assets/icons/conditionIcons/338.png'),
  'Ice pellets': require('../assets/icons/conditionIcons/350.png'),
  'Light rain shower': require('../assets/icons/conditionIcons/353.png'),
  'Moderate or heavy rain shower': require('../assets/icons/conditionIcons/356.png'),
  'Torrential rain shower': require('../assets/icons/conditionIcons/359.png'),
  'Light sleet showers': require('../assets/icons/conditionIcons/362.png'),
  'Moderate or heavy sleet showers': require('../assets/icons/conditionIcons/365.png'),
  'Light snow showers': require('../assets/icons/conditionIcons/368.png'),
  'Moderate or heavy snow showers': require('../assets/icons/conditionIcons/371.png'),
  'Light showers of ice pellets': require('../assets/icons/conditionIcons/374.png'),
  'Moderate or heavy showers of ice pellets': require('../assets/icons/conditionIcons/377.png'),
  'Patchy light rain with thunder': require('../assets/icons/conditionIcons/386.png'),
  'Moderate or heavy rain with thunder': require('../assets/icons/conditionIcons/389.png'),
  'Patchy light snow with thunder': require('../assets/icons/conditionIcons/392.png'),
  'Moderate or heavy snow with thunder': require('../assets/icons/conditionIcons/395.png'),
};
